/*
 * Shared WebRTC helpers
 * Copyright (c) 2026 The FFmpeg Project
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#ifndef AVFORMAT_RTC_H
#define AVFORMAT_RTC_H

#include <stdint.h>
#include <stddef.h>

#include "libavutil/lfg.h"

#include "avformat.h"
#include "url.h"

/**
 * Maximum size limit of a Session Description Protocol (SDP),
 * be it an offer or answer.
 */
#define RTC_MAX_SDP_SIZE 8192

/**
 * The size of the Secure Real-time Transport Protocol (SRTP) master key material
 * that is exported by Secure Sockets Layer (SSL) after a successful Datagram
 * Transport Layer Security (DTLS) handshake. This material consists of a key
 * of 16 bytes and a salt of 14 bytes.
 */
#define RTC_DTLS_SRTP_KEY_LEN 16
#define RTC_DTLS_SRTP_SALT_LEN 14

/**
 * The maximum size of the Secure Real-time Transport Protocol (SRTP) HMAC checksum
 * and padding that is appended to the end of the packet. To calculate the maximum
 * size of the User Datagram Protocol (UDP) packet that can be sent out, subtract
 * this size from the `pkt_size`.
 */
#define RTC_DTLS_SRTP_CHECKSUM_LEN 16

/**
 * The STUN message header, which is 20 bytes long, comprises the
 * STUNMessageType (1B), MessageLength (2B), MagicCookie (4B),
 * and TransactionID (12B).
 * See https://datatracker.ietf.org/doc/html/rfc5389#section-6
 */
#define RTC_STUN_HEADER_SIZE 20

/**
 * The RTP header is 12 bytes long, comprising the Version(1B), PT(1B),
 * SequenceNumber(2B), Timestamp(4B), and SSRC(4B).
 * See https://www.rfc-editor.org/rfc/rfc3550#section-5.1
 */
#define RTC_RTP_HEADER_SIZE 12

/**
 * For RTCP, PT is [128, 223] (or without marker [0, 95]). Literally, RTCP starts
 * from 64 not 0, so PT is [192, 223] (or without marker [64, 95]), see "RTCP Control
 * Packet Types (PT)" at
 * https://www.iana.org/assignments/rtp-parameters/rtp-parameters.xhtml#rtp-parameters-4
 *
 * For RTP, the PT is [96, 127], or [224, 255] with marker. See "RTP Payload Types (PT)
 * for standard audio and video encodings" at
 * https://www.iana.org/assignments/rtp-parameters/rtp-parameters.xhtml#rtp-parameters-1
 */
#define RTC_RTCP_PT_START 192
#define RTC_RTCP_PT_END   223

typedef struct RTCICEContext {
    /* The random number generator. */
    AVLFG *rnd;
    /* The ICE username and pwd fragment generated by the muxer. */
    char *local_ufrag;
    char *local_pwd;
    /* The ICE username and pwd from remote server. */
    char *remote_ufrag;
    char *remote_pwd;
    uint64_t tie_breaker; // random 64 bit, for ICE-CONTROLLING
} RTCICEContext;

int ff_rtc_ice_create_binding_request(void *logctx, RTCICEContext *ice,
                                      uint8_t *buf, int buf_size,
                                      int *request_size);
int ff_rtc_ice_create_binding_response(void *logctx, RTCICEContext *ice,
                                       char *tid, int tid_size,
                                       uint8_t *buf, int buf_size,
                                       int *response_size);
int ff_rtc_ice_is_binding_request(uint8_t *b, int size);
int ff_rtc_ice_is_binding_response(uint8_t *b, int size);

int ff_rtc_is_rtp_or_rtcp(const uint8_t *b, int size);
int ff_rtc_is_rtcp(const uint8_t *b, int size);

int ff_rtc_init_certificate(void *logctx, char *key_file,
                            char *cert_file, char *key_buf,
                            size_t key_buf_size, char *cert_buf,
                            size_t cert_buf_size, char **fingerprint);
int ff_rtc_dtls_open(void *logctx, AVFormatContext *s, URLContext **dtls_uc,
                     URLContext *udp, char *ice_host, int ice_port, int pkt_size,
                     char *cert_file, char *key_file,
                     char *cert_buf, char *key_buf,
                     int is_dtls_active);
#endif /* AVFORMAT_RTC_H */
