/*
 * Shared WebRTC helpers
 * Copyright (c) 2026 The FFmpeg Project
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#ifndef AVFORMAT_RTC_H
#define AVFORMAT_RTC_H

#include <stdint.h>
#include <stddef.h>

#include "libavutil/lfg.h"

#include "avformat.h"
#include "url.h"

/**
 * Maximum size limit of a Session Description Protocol (SDP),
 * be it an offer or answer.
 */
#define RTC_MAX_SDP_SIZE 8192

/**
 * The size of the Secure Real-time Transport Protocol (SRTP) master key material
 * that is exported by Secure Sockets Layer (SSL) after a successful Datagram
 * Transport Layer Security (DTLS) handshake. This material consists of a key
 * of 16 bytes and a salt of 14 bytes.
 */
#define RTC_DTLS_SRTP_KEY_LEN 16
#define RTC_DTLS_SRTP_SALT_LEN 14

/**
 * The maximum size of the Secure Real-time Transport Protocol (SRTP) HMAC checksum
 * and padding that is appended to the end of the packet. To calculate the maximum
 * size of the User Datagram Protocol (UDP) packet that can be sent out, subtract
 * this size from the `pkt_size`.
 */
#define RTC_DTLS_SRTP_CHECKSUM_LEN 16

/**
 * The STUN message header, which is 20 bytes long, comprises the
 * STUNMessageType (1B), MessageLength (2B), MagicCookie (4B),
 * and TransactionID (12B).
 * See https://datatracker.ietf.org/doc/html/rfc5389#section-6
 */
#define RTC_STUN_HEADER_SIZE 20

/**
 * The RTP header is 12 bytes long, comprising the Version(1B), PT(1B),
 * SequenceNumber(2B), Timestamp(4B), and SSRC(4B).
 * See https://www.rfc-editor.org/rfc/rfc3550#section-5.1
 */
#define RTC_RTP_HEADER_SIZE 12

/**
 * For RTCP, PT is [128, 223] (or without marker [0, 95]). Literally, RTCP starts
 * from 64 not 0, so PT is [192, 223] (or without marker [64, 95]), see "RTCP Control
 * Packet Types (PT)" at
 * https://www.iana.org/assignments/rtp-parameters/rtp-parameters.xhtml#rtp-parameters-4
 *
 * For RTP, the PT is [96, 127], or [224, 255] with marker. See "RTP Payload Types (PT)
 * for standard audio and video encodings" at
 * https://www.iana.org/assignments/rtp-parameters/rtp-parameters.xhtml#rtp-parameters-1
 */
#define RTC_RTCP_PT_START 192
#define RTC_RTCP_PT_END   223

enum RTCState {
    RTC_STATE_NONE,

    /* The initial state. */
    RTC_STATE_INIT,
    /* The muxer has sent the offer to the peer. */
    RTC_STATE_OFFER,
    /* The muxer has received the answer from the peer. */
    RTC_STATE_ANSWER,
    /**
     * After parsing the answer received from the peer, the muxer negotiates the abilities
     * in the offer that it generated.
     */
    RTC_STATE_NEGOTIATED,
    /* The muxer has connected to the peer via UDP. */
    RTC_STATE_UDP_CONNECTED,
    /* The muxer has sent the ICE request to the peer. */
    RTC_STATE_ICE_CONNECTING,
    /* The muxer has received the ICE response from the peer. */
    RTC_STATE_ICE_CONNECTED,
    /* The muxer has finished the DTLS handshake with the peer. */
    RTC_STATE_DTLS_FINISHED,
    /* The muxer has finished the SRTP setup. */
    RTC_STATE_SRTP_FINISHED,
    /* The muxer is ready to send/receive media frames. */
    RTC_STATE_READY,
    /* The muxer is failed. */
    RTC_STATE_FAILED,
};

typedef struct RTCContext {
    AVFormatContext *ctx;

    enum RTCState state;

    /* The random number generator. */
    AVLFG rnd;

    /* The ICE username and pwd fragment generated by the muxer. */
    char ice_ufrag_local[9];
    char ice_pwd_local[33];

    int is_peer_ice_lite;
    uint64_t ice_tie_breaker; // random 64 bit, for ICE-CONTROLLING
    /* The ICE username and pwd from remote server. */
    char *ice_ufrag_remote;
    char *ice_pwd_remote;
    /**
     * This represents the ICE candidate protocol, priority, host and port.
     * Currently, we only support one candidate and choose the first UDP candidate.
     * However, we plan to support multiple candidates in the future.
     */

    /* TODO: Use AVIOContext instead of URLContext */
    URLContext *dtls_uc;

    char *ice_protocol;
    char *ice_host;
    int ice_port;

    /* The fingerprint of certificate, used in SDP offer. */
    char *dtls_fingerprint;
    /* remote DTLS cert fingerprint from SDP answer (sha-256). */
    char *remote_fingerprint;

    /* The certificate and private key content used for DTLS handshake */
    char cert_buf[MAX_CERTIFICATE_SIZE];
    char key_buf[MAX_CERTIFICATE_SIZE];

    /* The certificate and private key used for DTLS handshake. */
    char* cert_file;
    char* key_file;

    /* The UDP transport is used for delivering ICE, DTLS and SRTP packets. */
    URLContext *udp;
    /**
     * The size of RTP packet, should generally be set to MTU.
     * Note that pion requires a smaller value, for example, 1200.
     */
    int pkt_size;
    int ts_buffer_size;/* Underlying protocol send/receive buffer size */

    uint16_t audio_first_seq;
    uint16_t video_first_seq;

    /* The SSRC of the audio and video stream, generated by the muxer. */
    uint32_t audio_ssrc;
    uint32_t video_ssrc;
    uint32_t video_rtx_ssrc;

    /* The PT(Payload Type) of stream, generated by the muxer. */
    uint8_t audio_payload_type;
    uint8_t video_payload_type;
    uint8_t video_rtx_payload_type;

    /* Parameters for the input audio and video codecs. */
    AVCodecParameters *audio_par;
    AVCodecParameters *video_par;

} RTCContext;

int rtc_init(RTCContext *rtc);

int ff_rtc_ice_create_binding_request(RTCContext *rtc,
                                      uint8_t *buf, int buf_size,
                                      int *request_size);
int ff_rtc_ice_create_binding_response(RTCContext *rtc,
                                       char *tid, int tid_size,
                                       uint8_t *buf, int buf_size,
                                       int *response_size);
int ff_rtc_ice_is_binding_request(uint8_t *b, int size);
int ff_rtc_ice_is_binding_response(uint8_t *b, int size);

int ff_rtc_is_rtp_or_rtcp(const uint8_t *b, int size);
int ff_rtc_is_rtcp(const uint8_t *b, int size);

int ff_rtc_init_certificate(RTCContext *rtc);
int ff_rtc_dtls_open(RTCContext *rtc, int is_dtls_active);
int ff_rtc_udp_connect(RTCContext *rtc);
int rtc_generate_sdp_offer(RTCContext *rtc, char **sdp_offer, int is_dtls_active);
#endif /* AVFORMAT_RTC_H */
